# Governance Baseline — {{PROJECT_NAME}}

<!--
This file is the project-level govern-claude skill's baseline. It records the
expected state of `.claude/`. govern-claude diffs the actual state against this
baseline to detect drift.

Auto-generated by meta-govern BOOTSTRAP. Update via meta-govern AUDIT or MIGRATE.
-->

## Generated
- Date: {{SCAFFOLD_DATE}}
- meta-govern version: {{META_GOVERN_VERSION}}
- Palier: {{CURRENT_PALIER}}
- DDD score: {{DDD_SCORE}}/16
- DDD decision: {{DDD_DECISION}}
- Stack: {{STACK_NAME}}

## Expected `.claude/` inventory

### Skills (project-level)
- brainstorm — design phase HARD GATE before implementation
- write-plan — plan phase HARD GATE before execution; rejects designs without delta
- execute-plan — 3-tier classification + Pipeline Task List + per-task implementer/reviewer
- quality-gate — deterministic 12-check + architectural review
- govern-claude — project-level audit against this baseline
- test-driven-development — RED → GREEN → REFACTOR per-task discipline

{{ADDITIONAL_SKILLS}}

### Agents (project-level)
- implementer — bulk task implementer (TDD-light), `model: sonnet`, `effort: medium`
- ui-implementer — premium UI/component implementer (invokes `ship-polished-ui` as its design doctrine), `model: sonnet`, `effort: high`
- spec-reviewer — foreground spec/AC alignment reviewer, `model: sonnet`, `effort: high`, `permissionMode: plan`
- code-quality-reviewer — foreground code-quality reviewer (10-point focus), `model: sonnet`, `effort: high`, `permissionMode: plan`
- persona-simulator — UX role-play between brainstorm sections, read-only
- codebase-reality-check — pre-Step-1 reality check for brainstorm, read-only

{{ADDITIONAL_AGENTS}}

### Hooks (project-level)
- session-start-env-check.mjs (SessionStart) — verify required tools (node, git, bun)
- track-workflow.mjs (PostToolUse Edit|Write|MultiEdit|Bash) — workflow state tracking
- enforce-workflow.mjs (Stop) — block Stop if validate not run since last edit; sous `MG_HEADLESS_RUN=1` exige `validate` inconditionnellement (gate durci des runs autonomes)
- precompact-handoff.mjs (PreCompact) — write HANDOFF.md
- postcompact-reinject.mjs (SessionStart, matcher: compact) — re-inject discipline if mid-plan-execution
- block-docs-markdown.mjs (PreToolUse Write|Edit|MultiEdit) — bloque tout `.md` sous `docs/`; route vers scaffold.mjs
- bash-write-guard.mjs (PreToolUse Bash) — dénie les écritures Bash vers un `.md` sous `docs/`, un chemin protégé ou `git add -A`; shadow-log les écritures `src/**` (promues deny sous `BASH_WRITE_GUARD_ENFORCE=1`)
- docs-index-refresh.mjs (Stop) — régénère `docs/index.html` si des docs ont changé; ne bloque jamais

{{ADDITIONAL_HOOKS}}

### Path-scoped rules (project-level)
- clean-code.md (paths: `src/**/*.{ts,tsx}`) — DRY/KISS/YAGNI/SOLID/SINE
- file-size-budget.md (paths: `src/**/*.{ts,tsx,js,jsx}`) — 300-line hard cap
- spec-protocol.md (paths: `docs/specs/**`, `docs/plans/**`) — delta protocol
- claude-config-style.md (paths: `.claude/**`) — anti-defensive-scaffolding (Claude 4.7+/5)
- parallel-dispatch.md (paths: ALL) — parallel agent dispatch discipline
- ui-components.md (paths: `src/**/components/**`, `pages/**`) — UI conventions {{IF_HAS_UI}}
- data-layer.md (paths: `src/**/data-layer/**` OR `convex/**`) — data layer rules {{IF_HAS_BACKEND}}
- testing.md (paths: `tests/**`, `**/*.test.*`) — testing rules

{{ADDITIONAL_RULES}}

### Scripts (project-level)
- file-size-growth-guard.mjs — pre-commit, blocks growth on over-budget files
- quality-checks/ — 12-check deterministic quality script
- setup-worktree.mjs — dynamic git worktree creation at `.claude/.worktrees/<name>/`
- docs-html/ — toolkit docs HTML (scaffold, make-index, inventory, convert, verify, rewrite-refs, no-markdown-guard + lib/docs-config)
- check-docs-map.mjs — valide `docs/docs-map.json` contre le disque

{{ADDITIONAL_SCRIPTS}}

## Expected source-of-truth docs

Tous les docs sous `docs/` sont HTML (doctrine HTML-first; aucun `.md`).

- `{{SPEC_DOC}}` — FUNC-XX, RA-XX, VAL-XX (CRITICAL)
- `{{DATA_MODEL_DOC}}` — schema, contracts (CRITICAL)
- `{{CATALOG_DOC}}` — C-XX components (CRITICAL)
- `docs/docs-map.json` — registre canonique des docs (CRITICAL)
- `docs/index.html` — hub généré (make-index)

{{ADDITIONAL_DOCS}}

## Expected package.json scripts

Generated add-if-missing by `bootstrap-project.mjs` (a project may already define
its own bodies — these are the meta-govern defaults). `typecheck` is added only
for TypeScript stacks and, when present, folded into `validate`/`validate:fast`.

- `dev` — local dev server
- `quality:check` — full deterministic quality scan (`quality-checks/index.mjs`)
- `quality:check:staged` — staged-only scan (`--scope staged --fail-level high`)
- `size-guard` — file-size-growth-guard
- `typecheck` — type-check, no emit (TS stacks only)
- `test` — the project's test runner
- `validate` — `quality:check && size-guard [&& typecheck] && test && mark-validate-pass.mjs` (the LAST step writes the Stop-gate success sentinel)
- `validate:fast` — `quality:check [&& typecheck]` (no size-guard / tests)
- `docs:index` — régénère `docs/index.html` (make-index)
- `docs-map:check` — valide `docs/docs-map.json`
- `docs:check` — no-markdown-guard (aucun `.md` sous `docs/`)
- `predeploy` — predeploy-check (compensation locale de CI serveur quand `ciPolicy = local-compensation`)

## Expected `.husky/pre-commit`

Gate runs on STAGED/changed code only, via `node` (scripts are `.mjs`, not pm
sub-commands):

```bash
node .claude/scripts/file-size-growth-guard.mjs
node .claude/scripts/quality-checks/index.mjs --scope staged --fail-level high
node .claude/scripts/docs-html/no-markdown-guard.mjs
node .claude/scripts/check-docs-map.mjs
```

Compensation CI locale (quand `ciPolicy = local-compensation` dans `.claude/.meta-govern.json`) :
en l'absence de CI serveur, la couverture tient sur deux briques locales — `predeploy-check.mjs`
(scan complet avant tout déploiement, lancé via `npm run predeploy`) et le gate Stop durci
(`enforce-workflow.mjs` sous `MG_HEADLESS_RUN=1`, qui exige `validate` inconditionnellement sur
les runs autonomes). audit-project présente alors le CI serveur en OPTION, non en manquement.

## Expected `.gitignore` additions

```
.claude/settings.local.json
.claude/tmp/
.claude/.worktrees/
HANDOFF.md
```

## Drift detection

govern-claude checks:
- All entries above exist (no missing artifacts)
- No orphans (skills/agents/hooks/rules NOT in this baseline → flag for promotion or removal)
- No oversized files (skill body >5K words, rule >50 lines, CLAUDE.md >120 lines)
- No defensive scaffolding patterns ("MUST", "ALWAYS", "double-check", "n'oublie pas")
- All hooks declared in settings.json have scripts on disk
- All `.claude/rules/*.md` have `paths:` frontmatter
- No `@filename` imports in CLAUDE.md
- No README.md files in skill folders
- All agents have explicit `effort:` frontmatter
- All hooks have macOS-hardened PATH
- Aucun `.md` sous `docs/` (no-markdown-guard exit 0; doctrine HTML-first)
- Every project-authored hook/guard ships a test couvrant un cas POSITIF (bloque l'interdit) ET un cas NÉGATIF (laisse passer le légitime); inventaire zéro-hook-orphelin (chaque `.claude/hooks/*.mjs` référencé dans settings.json ou un frontmatter `.claude/agents/*.md`); `.claude/hooks/README.md` aligné sur les `.mjs` présents lorsqu'il existe (skip gracieux si absent)
- Parité runtime `.claude/` ↔ `.agents/` : chaque hook/skill/agent miroir existe des deux côtés en paires exactement identiques (dérive d'un seul runtime signalée)

## Evolution

Promotion to next palier (currently {{CURRENT_PALIER}} → {{CURRENT_PALIER_PLUS_1}}) requires:
{{NEXT_PALIER_TRIGGERS}}

Update this baseline when:
- meta-govern bumps major version → run MIGRATE
- New rule/hook/skill/agent added → re-run BOOTSTRAP add-only mode (or update manually + commit)
- Palier promoted → meta-govern updates this file with new artifacts
