# HANDOFF — Generated {{TIMESTAMP}}

<!-- This file is auto-generated by .claude/hooks/precompact-handoff.mjs.
     Do not manually edit; the next PreCompact will overwrite. -->

## Branch
{{BRANCH}}

## Modified files (top 40)
{{MODIFIED_FILES}}

## Active plans
{{ACTIVE_PLANS}}

## Latest design
{{LATEST_DESIGN}}

## Trigger reason
{{TRIGGER_REASON}}

## Resume instructions
1. Read this file (`HANDOFF.md`)
2. Read `CLAUDE.md`
3. If active plans exist, read the most recent one and resume from the first unchecked task
4. If active design exists with no plan yet, run `/write-plan`
5. Otherwise, ask the user what they'd like to focus on

## Discipline rules (re-read after compaction)

- Foreground reviews only — never dispatch reviewers in background
- Dispatch != done — work being completed by a subagent doesn't mean findings are addressed
- Groups are barriers — don't start group N+1 until group N's findings have been disposed
- Review fix loop: every finding gets Fixed (with re-run) or Deferred (new DEFERRED-XXX entry)
- Every finding needs a disposition; no silent dropping
- File-size cap: 300 lines (extraction via dot-notation siblings if larger)
- Source-of-truth delta required in every design; Task 1 of every plan = "Apply delta"
